function [outputArg1] = antsregles(path,mnipath,t1_name,dwi_name,lesion_name)

    
    outputArg1=1;
    ['Start mapping dwi to t1']
    syscode=['git-bash.exe antsRegistrationSyNQuick.sh -d 3 -f ',...
        path,dwi_name,'.nii.gz -m ',...
        path,t1_name,'.nii.gz -o ',...
        path,t1_name,'_to_dwi'];
    system(strrep(syscode,'\','/'));
    ['Mapping dwi to t1 finished']
    
    ['Start mapping t1 to MNI']
    systemcode=['git-bash.exe antsRegistrationSyNQuick.sh -d 3 -f ',...
        mnipath,'MNI152_T1_1mm.nii.gz -m ',...
        path,t1_name,'.nii.gz -o ',...
        path,t1_name,'_to_MNI152'];
    system(strrep(systemcode,'\','/'));
    ['Mapping t1 to MNI finished']
    
    ['Start mapping lesion to MNI']
    system(['antsApplyTransforms.exe -d 3 -i ',...
        path,lesion_name,'.nii.gz -r ',...
        mnipath,'MNI152_T1_1mm.nii.gz -o ',...
        path,lesion_name,'_to_MNI152_1mm.nii.gz -t ',...
        path,t1_name,'_to_MNI1521Warp.nii.gz -t ',...
        path,t1_name,'_to_MNI1520GenericAffine.mat  -t ',...
        '[',path,t1_name,'_to_dwi0GenericAffine.mat, 1] -t ',...
        path,t1_name,'_to_dwi1InverseWarp.nii.gz ']);
    system(['ImageMath.exe 3 ',...
        path,lesion_name,'_to_MNI152_1mm_thr.nii.gz m ',...
        path,lesion_name,'_to_MNI152_1mm.nii.gz ',...
        mnipath,'MNI152_T1_1mm_brain.nii']);
    system(['ThresholdImage.exe 3 ',...
        path,lesion_name,'_to_MNI152_1mm_thr.nii.gz ',...
        path,lesion_name,'_to_MNI152_1mm_thr.nii.gz 0 0 0 1']);
    ['Mapping lesion to MNI finished']
    
    for i=2:3
        re=num2str(i);
        ['Start mapping MNI1mm to ',re,'mm']
        system(['antsApplyTransforms.exe -d 3 -i ',...
            path,lesion_name,'_to_MNI152_1mm.nii.gz -r ',...
            mnipath,'MNI152_T1_',re,'mm_brain.nii -o ',...
            path,lesion_name,'_to_MNI152_',re,'mm.nii.gz -t ',...
            mnipath,'MNI1mm_to_',re,'mm1Warp.nii.gz -t ',...
            mnipath,'MNI1mm_to_',re,'mm0GenericAffine.mat '])
        system(['ImageMath.exe 3 ',...
            path,lesion_name,'_to_MNI152_',re,'mm_thr.nii.gz m ',...
            path,lesion_name,'_to_MNI152_',re,'mm.nii.gz ',...
            mnipath,'MNI152_T1_',re,'mm_brain.nii']);
        system(['ThresholdImage.exe 3 ',...
            path,lesion_name,'_to_MNI152_',re,'mm_thr.nii.gz ',...
            path,lesion_name,'_to_MNI152_',re,'mm_thr.nii.gz 0 0 0 1']);
        ['Mapping MNI1mm to ',re,'mm finished']
    end
    
    system(['mkdir ',path,'tmp']);
    di=dir([path,'*to*']);
    for i=1:length(di)
        if ~contains(di(i).name,'mm_thr')
            movefile([path,di(i).name],[path,'tmp\',di(i).name]);%把中间文件存到tmp文件夹里
        end
    end
    if isempty(dir([path,'*3mm_thr*']))
        ['error occured during registration']
        outputArg1=0;
    end
end

